Fix build failure with new method to get pid
ballerinalang/tools-distribution pull request #142
Opened 2017-08-14 13:28 UTC by lankavitharana

2017-08-14 15:11 UTC, yasassri approved these changes

2017-08-14 15:21 UTC, yasassri commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                tmp = Runtime.getRuntime().exec("lsof -Pi tcp:" + httpServerPort);
lsof -ti tcp:9090 will give the PID, Is there any reason for not using this?

2017-08-15 03:33 UTC, chanakaudaya requested changes

2017-08-15 03:33 UTC, chanakaudaya commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                    continue;
@lankavitharana Check the command mentioned by @yasassri . It directly gives the PID. you don't need to do the string manipulations which you have done here.

2017-08-15 05:12 UTC, lankavitharana commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                tmp = Runtime.getRuntime().exec("lsof -Pi tcp:" + httpServerPort);
no special reason, but when trying to list processes using the given port, it shows both listening processes and also connected processes, hence need to filter only the listening process.

2017-08-15 05:26 UTC, lankavitharana commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                    continue;
checked that, I think we can't even use that, the reason is, it too gives both listening and connected processes PIDs and we cannot distinguish which is which( there may be other best approaches out there to do this directly, but didn't came across anything yet)

2017-08-15 05:29 UTC, lankavitharana commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                    continue;
And I think we should do some refactoring to current integration tests, this PR is a quick solution to the current tools distribution build failure

2017-08-15 07:22 UTC, yasassri commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                tmp = Runtime.getRuntime().exec("lsof -Pi tcp:" + httpServerPort);
@lankavitharana Shall we try the below command,
```
String[] cmd = { "/bin/sh", "-c",
                        "lsof -Pi tcp:" + httpServerPort + " | grep LISTEN | awk \'{print $2}\'" };
tmp = Runtime.getRuntime().exec(cmd);
```
and then to get the PID,
```
 String outPut = readProcessInputStream(tmp.getInputStream());
            pid = outPut.split("\n")[0];
```

2017-08-15 08:03 UTC, lankavitharana commented on modules/tests/test-integration/src/test/java/org/ballerinalang/test/context/ServerInstance.java
> +                tmp = Runtime.getRuntime().exec("lsof -Pi tcp:" + httpServerPort);
Added that thanks @yasassri  for the point on how to use grep within exec command

2017-08-15 08:40 UTC, chanakaudaya approved these changes

2017-08-15 08:40 UTC, merged